builds:
- id: kubectl-sick-pods
  env:
  - CGO_ENABLED=0
  main: ./cmd/kubectl-sick-pods/main.go
  binary: kubectl-sick-pods
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
archives:
- builds:
  - kubectl-sick-pods
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  files:
  - LICENSE
